//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpdesk_v2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Helpdesk_v2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D_Vestiging.
        /// </summary>
        internal static string D_Vestiging {
            get {
                return ResourceManager.GetString("D_Vestiging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Persoon.
        /// </summary>
        internal static string I_Persoon {
            get {
                return ResourceManager.GetString("I_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I_Vestiging.
        /// </summary>
        internal static string I_Vestiging {
            get {
                return ResourceManager.GetString("I_Vestiging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_Vestiging.
        /// </summary>
        internal static string S_Vestiging {
            get {
                return ResourceManager.GetString("S_Vestiging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Persoon.
        /// </summary>
        internal static string U_Persoon {
            get {
                return ResourceManager.GetString("U_Persoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U_Vestiging.
        /// </summary>
        internal static string U_Vestiging {
            get {
                return ResourceManager.GetString("U_Vestiging", resourceCulture);
            }
        }
    }
}
